### ISSUE TITLE
Windows Defender sending mod-tools to quarantine 

### ISSUE THREAD

**Issue by AlexiBlue** [customskinlol/cslol-manager#1]
![image](https://user-images.githubusercontent.com/66726088/161381667-cdb83297-dd87-4db1-a46d-4487c3806f20.png)

(Here i tried to paste it out of the archive, but it still got deleted in the cslol-tools folder)

**Comment by RaresGIT** [comment]
Same behaviour here, can be bypassed for now by disabling real time protection. I think the fix is to include some sort of publisher header in the official .exe release

**Comment by moonshadow565** [comment]
Might have a clue on what is causing this to trip machine learning

This is control build (should behave same as current release):
https://github.com/customskinlol/cslol-manager/suites/5909082685/artifacts/201502951

This is version without windows 7 workaround:
https://github.com/customskinlol/cslol-manager/suites/5909080261/artifacts/201502717

**Comment by RaresGIT** [comment]
> 

This version actually works! The mod-tools doesn't get flagged by Windows Defender. Is there then something the CD pipeline on GitHub adds that breaks the build?

**Comment by moonshadow565** [comment]
Its workaround for Windows 7 + Riot AC that triggers it!!

**Comment by moonshadow565** [comment]
This is version with windows 7 support partially restored:
https://github.com/customskinlol/cslol-manager/suites/5909241989/artifacts/201515758

**Comment by AlexiBlue** [comment]
The workaround was to just click "actions" and "restore", but i thought it'd be good to let the dev know about the issue
