### ISSUE TITLE
does not start

### ISSUE THREAD

**Issue by kakota1234** [customskinlol/cslol-manager#10]
[INFO] Version: 2022-05-25-570e963
[INFO] Status changed: Acquire lock
[INFO] Status changed: Check mod-tools
[INFO] Status changed: Load mods
[INFO] Status changed: Load profiles
[INFO] Status changed: Read profile
[INFO] Status changed: Change League Path
[INFO] Status changed: Save profile
[INFO] Status changed: Write profile
[EXTERNAL] 18:04:05.075 INF[288   ] Indexing game
[EXTERNAL] 18:04:05.263 WRN[288   ] Failed to open game wad file C:/Riot Games/League of Legends/Game/DATA/FINAL/Champions/TFTChampion.pt_BR.wad.client: Empty wad file
[EXTERNAL] 18:04:05.422 INF[288   ] Reading mods
[EXTERNAL] 18:04:05.422 INF[288   ] Merging mods
[EXTERNAL] 18:04:05.422 INF[288   ] Writing wads
[EXTERNAL] 18:04:05.423 INF[288   ] Cleaning up stray wads
[EXTERNAL] 18:04:05.477 INF[288   ] Done!
[INFO] Status changed: Starting patcher...
[INFO] Status changed: Waiting for league match to start
[INFO] Status changed: Installing Mod
[EXTERNAL] 18:04:22.416 INF[3436  ] Creating tmp directory
[EXTERNAL] 18:04:22.417 INF[3436  ] Unzipping mod
[EXTERNAL] 18:04:23.301 INF[3436  ] Optimizing after unzipping
[EXTERNAL] 18:04:23.301 INF[3436  ] Creating tmp directory
[EXTERNAL] 18:04:23.302 INF[3436  ] Indexing mod wads
[EXTERNAL] 18:04:23.305 INF[3436  ] Indexing game wads
[EXTERNAL] 18:04:23.487 WRN[3436  ] Failed to open game wad file C:/Riot Games/League of Legends/Game/DATA/FINAL/Champions/TFTChampion.pt_BR.wad.client: Empty wad file
[EXTERNAL] 18:04:23.650 INF[3436  ] Rebasing wads
[EXTERNAL] 18:04:23.706 INF[3436  ] Resolving conflicts
[EXTERNAL] 18:04:23.706 INF[3436  ] Copying META files
[EXTERNAL] 18:04:23.707 INF[3436  ] Writing wads
[EXTERNAL] 18:04:23.708 INF[3436  ] Writing wad: WAD/DATA2.wad.client
[EXTERNAL] 18:04:23.723 INF[3436  ] Writing wad: WAD/Map11.wad.client
[EXTERNAL] 18:04:23.732 INF[3436  ] Removing original directory
[EXTERNAL] 18:04:23.735 INF[3436  ] Moving tmp directory
[EXTERNAL] 18:04:23.735 INF[3436  ] Moving tmp directory
[EXTERNAL] 18:04:23.736 INF[3436  ] Done!
[INFO] Status changed: Save profile
[INFO] Status changed: Write profile
[EXTERNAL] 18:05:24.404 INF[2272  ] Indexing game
[EXTERNAL] 18:05:24.599 WRN[2272  ] Failed to open game wad file C:/Riot Games/League of Legends/Game/DATA/FINAL/Champions/TFTChampion.pt_BR.wad.client: Empty wad file
[EXTERNAL] 18:05:24.774 INF[2272  ] Reading mods
[EXTERNAL] 18:05:24.775 INF[2272  ] Merging mods
[EXTERNAL] 18:05:24.804 INF[2272  ] Writing wads
[EXTERNAL] 18:05:24.805 INF[2272  ] Writing wad: DATA/FINAL/DATA2.wad.client
[EXTERNAL] 18:05:25.754 INF[2272  ] Writing wad: DATA/FINAL/Maps/Shipping/Map11.wad.client
[EXTERNAL] 18:05:37.441 INF[2272  ] Writing wad: DATA/FINAL/Maps/Shipping/Map12.wad.client
[EXTERNAL] 18:05:55.949 INF[2272  ] Cleaning up stray wads
[EXTERNAL] 18:05:56.175 INF[2272  ] Done!
[INFO] Status changed: Starting patcher...
[INFO] Status changed: Found League
[INFO] Status changed: Wait initialized
[INFO] Status changed: Scanning
[INFO] Status changed: Saving
[INFO] Status changed: Patching
[EXTERNAL] Config: patcher-win32-v11 checksum:01937976 open:00f39260 open_ref:00920482 wopen:00f39198 ret:0091e591 alloc_ptr:01861730 alloc_fn:00ef8e5e
[ERROR] Exit with error: Run mod-tools
backtrace: 
  lol::patcher::Process::WriteMemory:
    address = 0x2c41730
    src = 0x1ced78
    size = 0x4
  Context::patch:
  mod_runoverlay:
    overlay = ./profiles/Default Profile
    config_file = ./profiles/Default Profile.config
    game = C:/Riot Games/League of Legends/Game
error: WriteProcessMemory: Par�metro incorreto.

**Comment by moonshadow565** [comment]
update to windows 10
