### ISSUE TITLE
newest update can't work

### ISSUE THREAD

**Issue by shadoxlans** [customskinlol/cslol-manager#12]
[INFO] Version: 2022-05-25-570e963
[INFO] Status changed: Acquire lock
[INFO] Status changed: Check mod-tools
[INFO] Status changed: Load mods
[INFO] Status changed: Load profiles
[INFO] Status changed: Read profile
[INFO] Status changed: Save profile
[INFO] Status changed: Write profile
[EXTERNAL] 02:41:47.560 INF[1536  ] Indexing game
[EXTERNAL] 02:41:51.179 WRN[1536  ] Failed to open game wad file C:/morgan/garena/32775/Game/DATA/FINAL/Champions/TFTChampion.en_US.wad.client: Empty wad file
[EXTERNAL] 02:41:51.180 WRN[1536  ] Failed to open game wad file C:/morgan/garena/32775/Game/DATA/FINAL/Champions/TFTChampion.zh_TW.wad.client: Empty wad file
[EXTERNAL] 02:41:52.586 INF[1536  ] Reading mods
[EXTERNAL] 02:41:53.484 WRN[1536  ] Compressed checksum conflict: 0xe25df4836bc882d in WAD/Lissandra.wad.client
[EXTERNAL] 02:41:53.485 WRN[1536  ] Compressed checksum conflict: 0x1c3b88a76923b2b0 in WAD/Lissandra.wad.client
[EXTERNAL] 02:41:53.487 WRN[1536  ] Compressed checksum conflict: 0x3d966b518e57b039 in WAD/Lissandra.wad.client
[EXTERNAL] 02:41:53.488 WRN[1536  ] Compressed checksum conflict: 0x43247315fada1304 in WAD/Lissandra.wad.client
[EXTERNAL] 02:41:53.489 WRN[1536  ] Compressed checksum conflict: 0x452e7db3bd44d9f4 in WAD/Lissandra.wad.client
[EXTERNAL] 02:41:53.489 WRN[1536  ] Compressed checksum conflict: 0x48eb06f1213b62dd in WAD/Lissandra.wad.client
[EXTERNAL] 02:41:53.491 WRN[1536  ] Compressed checksum conflict: 0x4d2fd27cffe98d71 in WAD/Lissandra.wad.client
[EXTERNAL] 02:41:53.491 WRN[1536  ] Compressed checksum conflict: 0x4f837102c34d8e17 in WAD/Lissandra.wad.client
[EXTERNAL] 02:41:53.493 WRN[1536  ] Compressed checksum conflict: 0x50a968451494cb8d in WAD/Lissandra.wad.client
[EXTERNAL] 02:41:53.536 WRN[1536  ] Compressed checksum conflict: 0x55ebc424c53e2147 in WAD/Lissandra.wad.client
[EXTERNAL] 02:41:53.537 WRN[1536  ] Compressed checksum conflict: 0x5b52685418044b30 in WAD/Lissandra.wad.client
[EXTERNAL] 02:41:53.537 WRN[1536  ] Compressed checksum conflict: 0x63560dcdccb9cdf7 in WAD/Lissandra.wad.client
[EXTERNAL] 02:41:53.539 WRN[1536  ] Compressed checksum conflict: 0x687714b82b361f57 in WAD/Lissandra.wad.client
[EXTERNAL] 02:41:53.546 WRN[1536  ] Compressed checksum conflict: 0x6b56ecac414a6ba6 in WAD/Lissandra.wad.client
[EXTERNAL] 02:41:53.547 WRN[1536  ] Compressed checksum conflict: 0x6cdbbba19cdd2ba2 in WAD/Lissandra.wad.client
[EXTERNAL] 02:41:53.549 WRN[1536  ] Compressed checksum conflict: 0x75e04c822cf3f5a0 in WAD/Lissandra.wad.client
[EXTERNAL] 02:41:53.551 WRN[1536  ] Compressed checksum conflict: 0x780bec2bbffc8d95 in WAD/Lissandra.wad.client
[EXTERNAL] 02:41:53.552 WRN[1536  ] Compressed checksum conflict: 0x8098778805223d08 in WAD/Lissandra.wad.client
[EXTERNAL] 02:41:53.559 WRN[1536  ] Compressed checksum conflict: 0x9164f69113ed03ec in WAD/Lissandra.wad.client
[EXTERNAL] 02:41:53.560 WRN[1536  ] Compressed checksum conflict: 0x9bc46ec392178d0a in WAD/Lissandra.wad.client
[EXTERNAL] 02:41:53.562 WRN[1536  ] Compressed checksum conflict: 0xb2ee077323e02931 in WAD/Lissandra.wad.client
[EXTERNAL] 02:41:53.564 WRN[1536  ] Compressed checksum conflict: 0xb7d98396fb797e40 in WAD/Lissandra.wad.client
[EXTERNAL] 02:41:53.564 WRN[1536  ] Compressed checksum conflict: 0xc1373edc94f8bc47 in WAD/Lissandra.wad.client
[EXTERNAL] 02:41:53.565 WRN[1536  ] Compressed checksum conflict: 0xc38578690e442e64 in WAD/Lissandra.wad.client
[EXTERNAL] 02:41:53.567 WRN[1536  ] Compressed checksum conflict: 0xcd402e2ba7644c9e in WAD/Lissandra.wad.client
[EXTERNAL] 02:41:53.568 WRN[1536  ] Compressed checksum conflict: 0xd1ac6d5eaddcf1d3 in WAD/Lissandra.wad.client
[EXTERNAL] 02:41:53.569 WRN[1536  ] Compressed checksum conflict: 0xd8589b75b9102049 in WAD/Lissandra.wad.client
[EXTERNAL] 02:41:53.570 WRN[1536  ] Compressed checksum conflict: 0xf14d64d54fef1ecb in WAD/Lissandra.wad.client
[EXTERNAL] 02:41:53.571 WRN[1536  ] Compressed checksum conflict: 0xf6703b4a5148c3d3 in WAD/Lissandra.wad.client
[EXTERNAL] 02:41:53.572 WRN[1536  ] Compressed checksum conflict: 0xfa4e135097afc552 in WAD/Lissandra.wad.client
[EXTERNAL] 02:41:53.572 WRN[1536  ] Compressed checksum conflict: 0xfa8ae7a12917956d in WAD/Lissandra.wad.client
[EXTERNAL] 02:41:53.573 WRN[1536  ] Compressed checksum conflict: 0xfdf0c7ebae932e59 in WAD/Lissandra.wad.client
[EXTERNAL] 02:41:53.574 WRN[1536  ] Compressed checksum conflict: 0xff09d1fbbcad58ab in WAD/Lissandra.wad.client
[EXTERNAL] 02:41:53.574 WRN[1536  ] Compressed checksum conflict: 0xff849a6359ed4a26 in WAD/Lissandra.wad.client
[EXTERNAL] 02:41:54.219 WRN[1536  ] Compressed checksum conflict: 0xfb1768f7751ba765 in WAD/Ahri.wad.client
[EXTERNAL] 02:41:54.219 WRN[1536  ] Compressed checksum conflict: 0x7d1b65b70b8f00c in WAD/Ahri.wad.client
[EXTERNAL] 02:41:54.220 INF[1536  ] Merging mods
[EXTERNAL] 02:41:54.757 INF[1536  ] Writing wads
[EXTERNAL] 02:41:54.757 INF[1536  ] Writing wad: DATA/FINAL/Champions/Ahri.wad.client
[EXTERNAL] 02:41:54.774 INF[1536  ] Writing wad: DATA/FINAL/Champions/Akali.wad.client
[EXTERNAL] 02:41:54.774 INF[1536  ] Writing wad: DATA/FINAL/Champions/Akshan.wad.client
[EXTERNAL] 02:41:54.775 INF[1536  ] Writing wad: DATA/FINAL/Champions/Annie.wad.client
[EXTERNAL] 02:41:54.788 INF[1536  ] Writing wad: DATA/FINAL/Champions/Aphelios.wad.client
[EXTERNAL] 02:41:54.789 INF[1536  ] Writing wad: DATA/FINAL/Champions/Ashe.wad.client
[EXTERNAL] 02:41:54.789 INF[1536  ] Writing wad: DATA/FINAL/Champions/Caitlyn.wad.client
[EXTERNAL] 02:41:54.790 INF[1536  ] Writing wad: DATA/FINAL/Champions/Camille.wad.client
[EXTERNAL] 02:41:54.803 INF[1536  ] Writing wad: DATA/FINAL/Champions/Cassiopeia.wad.client
[EXTERNAL] 02:41:54.804 INF[1536  ] Writing wad: DATA/FINAL/Champions/Diana.wad.client
[EXTERNAL] 02:41:54.805 INF[1536  ] Writing wad: DATA/FINAL/Champions/DrMundo.wad.client
[EXTERNAL] 02:41:54.805 INF[1536  ] Writing wad: DATA/FINAL/Champions/Elise.wad.client
[EXTERNAL] 02:41:54.806 INF[1536  ] Writing wad: DATA/FINAL/Champions/Evelynn.wad.client
[EXTERNAL] 02:41:54.807 INF[1536  ] Writing wad: DATA/FINAL/Champions/Fiora.wad.client
[EXTERNAL] 02:41:54.820 INF[1536  ] Writing wad: DATA/FINAL/Global.wad.client
[EXTERNAL] 02:41:54.821 INF[1536  ] Writing wad: DATA/FINAL/Champions/Gwen.wad.client
[EXTERNAL] 02:41:54.822 INF[1536  ] Writing wad: DATA/FINAL/Champions/Illaoi.wad.client
[EXTERNAL] 02:41:54.823 INF[1536  ] Writing wad: DATA/FINAL/Champions/Irelia.wad.client
[EXTERNAL] 02:41:54.824 INF[1536  ] Writing wad: DATA/FINAL/Champions/Janna.wad.client
[EXTERNAL] 02:41:54.825 INF[1536  ] Writing wad: DATA/FINAL/Champions/Jinx.wad.client
[EXTERNAL] 02:41:54.826 INF[1536  ] Writing wad: DATA/FINAL/Champions/Kaisa.wad.client
[EXTERNAL] 02:41:54.827 INF[1536  ] Writing wad: DATA/FINAL/Champions/Kalista.wad.client
[EXTERNAL] 02:41:54.844 INF[1536  ] Writing wad: DATA/FINAL/Champions/Karma.wad.client
[EXTERNAL] 02:41:54.862 INF[1536  ] Writing wad: DATA/FINAL/Champions/Katarina.wad.client
[EXTERNAL] 02:41:54.875 INF[1536  ] Writing wad: DATA/FINAL/Champions/Kayle.wad.client
[EXTERNAL] 02:41:54.882 INF[1536  ] Writing wad: DATA/FINAL/Champions/Kennen.wad.client
[EXTERNAL] 02:41:54.890 INF[1536  ] Writing wad: DATA/FINAL/Champions/Kindred.wad.client
[EXTERNAL] 02:41:54.898 INF[1536  ] Writing wad: DATA/FINAL/Champions/Leblanc.wad.client
[EXTERNAL] 02:41:54.909 INF[1536  ] Writing wad: DATA/FINAL/Champions/Leona.wad.client
[EXTERNAL] 02:41:54.915 INF[1536  ] Writing wad: DATA/FINAL/Champions/Lillia.wad.client
[EXTERNAL] 02:41:54.931 INF[1536  ] Writing wad: DATA/FINAL/Champions/Lissandra.wad.client
[EXTERNAL] 02:41:54.939 INF[1536  ] Writing wad: DATA/FINAL/Champions/Lux.wad.client
[EXTERNAL] 02:41:54.957 INF[1536  ] Writing wad: DATA/FINAL/Maps/Shipping/Map11.wad.client
[EXTERNAL] 02:41:54.967 INF[1536  ] Writing wad: DATA/FINAL/Maps/Shipping/Map12.wad.client
[EXTERNAL] 02:41:54.987 INF[1536  ] Writing wad: DATA/FINAL/Champions/MasterYi.wad.client
[EXTERNAL] 02:41:55.003 INF[1536  ] Writing wad: DATA/FINAL/Champions/MissFortune.wad.client
[EXTERNAL] 02:41:55.015 INF[1536  ] Writing wad: DATA/FINAL/Champions/Mordekaiser.wad.client
[EXTERNAL] 02:41:55.035 INF[1536  ] Writing wad: DATA/FINAL/Champions/Morgana.wad.client
[EXTERNAL] 02:41:55.057 INF[1536  ] Writing wad: DATA/FINAL/Champions/Nami.wad.client
[EXTERNAL] 02:41:55.061 INF[1536  ] Writing wad: DATA/FINAL/Champions/Neeko.wad.client
[EXTERNAL] 02:41:55.067 INF[1536  ] Writing wad: DATA/FINAL/Champions/Nidalee.wad.client
[EXTERNAL] 02:41:55.081 INF[1536  ] Writing wad: DATA/FINAL/Champions/Nunu.wad.client
[EXTERNAL] 02:41:55.089 INF[1536  ] Writing wad: DATA/FINAL/Champions/Orianna.wad.client
[EXTERNAL] 02:41:55.096 INF[1536  ] Writing wad: DATA/FINAL/Champions/Poppy.wad.client
[EXTERNAL] 02:41:55.107 INF[1536  ] Writing wad: DATA/FINAL/Champions/Qiyana.wad.client
[EXTERNAL] 02:41:55.117 INF[1536  ] Writing wad: DATA/FINAL/Champions/Quinn.wad.client
[EXTERNAL] 02:41:55.133 INF[1536  ] Writing wad: DATA/FINAL/Champions/RekSai.wad.client
[EXTERNAL] 02:41:55.138 INF[1536  ] Writing wad: DATA/FINAL/Champions/Rell.wad.client
[EXTERNAL] 02:41:55.150 INF[1536  ] Writing wad: DATA/FINAL/Champions/Riven.wad.client
[EXTERNAL] 02:41:55.159 INF[1536  ] Writing wad: DATA/FINAL/Champions/Samira.wad.client
[EXTERNAL] 02:41:55.162 INF[1536  ] Writing wad: DATA/FINAL/Champions/Sejuani.wad.client
[EXTERNAL] 02:41:55.166 INF[1536  ] Writing wad: DATA/FINAL/Champions/Senna.wad.client
[EXTERNAL] 02:41:55.177 INF[1536  ] Writing wad: DATA/FINAL/Champions/Seraphine.wad.client
[EXTERNAL] 02:41:55.185 INF[1536  ] Writing wad: DATA/FINAL/Shaders/Shaders.wad.client
[EXTERNAL] 02:41:55.190 INF[1536  ] Writing wad: DATA/FINAL/Champions/Shyvana.wad.client
[EXTERNAL] 02:41:55.200 INF[1536  ] Writing wad: DATA/FINAL/Champions/Sivir.wad.client
[EXTERNAL] 02:41:55.218 INF[1536  ] Writing wad: DATA/FINAL/Champions/Sona.wad.client
[EXTERNAL] 02:41:55.222 INF[1536  ] Writing wad: DATA/FINAL/Champions/Soraka.wad.client
[EXTERNAL] 02:41:55.231 INF[1536  ] Writing wad: DATA/FINAL/Champions/Swain.wad.client
[EXTERNAL] 02:41:55.244 INF[1536  ] Writing wad: DATA/FINAL/Champions/Syndra.wad.client
[EXTERNAL] 02:41:55.256 INF[1536  ] Writing wad: DATA/FINAL/Champions/Taliyah.wad.client
[EXTERNAL] 02:41:55.267 INF[1536  ] Writing wad: DATA/FINAL/Champions/Tristana.wad.client
[EXTERNAL] 02:41:55.285 INF[1536  ] Writing wad: DATA/FINAL/Champions/Vayne.wad.client
[EXTERNAL] 02:41:55.293 INF[1536  ] Writing wad: DATA/FINAL/Champions/Vex.wad.client
[EXTERNAL] 02:41:55.297 INF[1536  ] Writing wad: DATA/FINAL/Champions/Vi.wad.client
[EXTERNAL] 02:41:55.309 INF[1536  ] Writing wad: DATA/FINAL/Champions/Volibear.wad.client
[EXTERNAL] 02:41:55.326 INF[1536  ] Writing wad: DATA/FINAL/Champions/Xayah.wad.client
[EXTERNAL] 02:41:55.343 INF[1536  ] Writing wad: DATA/FINAL/Champions/Yuumi.wad.client
[EXTERNAL] 02:41:55.358 INF[1536  ] Writing wad: DATA/FINAL/Champions/Zeri.wad.client
[EXTERNAL] 02:41:55.363 INF[1536  ] Writing wad: DATA/FINAL/Champions/Zoe.wad.client
[EXTERNAL] 02:41:55.370 INF[1536  ] Writing wad: DATA/FINAL/Champions/Zyra.wad.client
[EXTERNAL] 02:41:55.377 INF[1536  ] Cleaning up stray wads
[EXTERNAL] 02:41:55.475 INF[1536  ] Done!
[INFO] Status changed: Starting patcher...
[INFO] Status changed: Found League
[INFO] Status changed: Wait patchable
[INFO] Status changed: Patching
[EXTERNAL] Config: patcher-win32-v11 checksum:01937976 open:00f39260 open_ref:00920482 wopen:00f39198 ret:0091e591 alloc_ptr:01861730 alloc_fn:00ef8e5e
[ERROR] Exit with error: Run mod-tools
backtrace: 
  lol::patcher::Process::WriteMemory:
    address = 0x28a1730
    src = 0x1deb38
    size = 0x4
  Context::patch:
  mod_runoverlay:
    overlay = ./profiles/Default Profile
    config_file = ./profiles/Default Profile.config
    game = C:/morgan/garena/32775/Game
error: WriteProcessMemory: �����e�`��
[INFO] Status changed: Save profile
[INFO] Status changed: Write profile
[EXTERNAL] 02:46:07.775 INF[10228 ] Indexing game
[EXTERNAL] 02:46:11.562 WRN[10228 ] Failed to open game wad file C:/morgan/garena/32775/Game/DATA/FINAL/Champions/TFTChampion.en_US.wad.client: Empty wad file
[EXTERNAL] 02:46:11.563 WRN[10228 ] Failed to open game wad file C:/morgan/garena/32775/Game/DATA/FINAL/Champions/TFTChampion.zh_TW.wad.client: Empty wad file
[EXTERNAL] 02:46:13.067 INF[10228 ] Reading mods
[EXTERNAL] 02:46:13.067 INF[10228 ] Merging mods
[EXTERNAL] 02:46:13.067 INF[10228 ] Writing wads
[EXTERNAL] 02:46:13.068 INF[10228 ] Cleaning up stray wads
[EXTERNAL] 02:46:13.155 INF[10228 ] Done!
[INFO] Status changed: Starting patcher...
[INFO] Status changed: Found League
[INFO] Status changed: Wait initialized
[INFO] Status changed: Scanning
[INFO] Status changed: Saving
[INFO] Status changed: Patching
[EXTERNAL] Config: patcher-win32-v11 checksum:01937976 open:00f39260 open_ref:00920482 wopen:00f39198 ret:0091e591 alloc_ptr:01861730 alloc_fn:00ef8e5e
[ERROR] Exit with error: Run mod-tools
backtrace: 
  lol::patcher::Process::WriteMemory:
    address = 0x28a1730
    src = 0x23e878
    size = 0x4
  Context::patch:
  mod_runoverlay:
    overlay = ./profiles/new
    config_file = ./profiles/new.config
    game = C:/morgan/garena/32775/Game
error: WriteProcessMemory: �����e�`��

**Comment by moonshadow565** [comment]
update to windows 10
