### ISSUE TITLE
i cant open lcs manager

### ISSUE THREAD

**Issue by MasterP42** [customskinlol/cslol-manager#13]
code execution cannot be continued because the VCRUNTIME140_1.dll object was not found Reinstalling the program may solve this problem.                 I tried to uninstall and install but it still does not work

**Comment by MasterP42** [comment]
the same with MSVCP140_1.dll

**Comment by moonshadow565** [comment]
update to windows 10
https://aka.ms/vs/17/release/vc_redist.x64.exe
