### ISSUE TITLE
it takes a long time to load the mods

### ISSUE THREAD

**Issue by carlosfelipe117** [customskinlol/cslol-manager#2]
One thing happens and that is that it takes a long time to load the mods when you hit "run" they take up to 5 or 10 minutes to load and also fill the ram memory while it is in the process of running the mods

**Comment by AlexiBlue** [comment]
The problem is most likely in the mods itself, it can be a mem-leak, straight-up code inefficiency, or your pc's hardware is just unable to process everything fast enough
