### ISSUE TITLE
Add on Windows Startup option for app

### ISSUE THREAD

**Issue by RaresGIT** [customskinlol/cslol-manager#3]
Would it be an idea to have an option that allows you to run the app on startup, and also automatically run the app?

**Comment by AlexiBlue** [comment]
Actually a great idea, i can not describe how many times i just opened the app and forgot to press "Run"
It can be a timed option as in "Running in 5...4...3..." and an option to cancel

**Comment by RaresGIT** [comment]
> Actually a great idea, i can not describe how many times i just opened the app and forgot to press "Run"
> It can be a timed option as in "Running in 5...4...3..." with an option to cancel
> Just make it a setting

I’m going to try to write the setting myself, wish me luck. Not that experienced with C++ but I think i can figure it out
